import { ArrowUpRight, BarChart3, ClipboardCheck, Clock3, Download, FileAudio, FileText, Gauge, GitCompareArrows, Home, LogOut, Play, Settings2, ShieldCheck, Users } from "lucide-react";
import { toast } from "sonner";
import type { EvaluationRecord, View } from "@/pages/Index";

type AdminDashboardProps = {
  evaluations: EvaluationRecord[];
  goTo: (view: View) => void;
  logout: () => void;
};

function BrandMark() {
  return <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-[#493879] to-[#8b5bc4] text-white shadow-sm"><span className="text-[13px] font-black">∿</span></div>;
}

const menu = [
  { label: "Dashboard", icon: Home },
  { label: "Users", icon: Users },
  { label: "Audio submissions", icon: FileAudio },
  { label: "Transcriptions", icon: FileText },
  { label: "Analytics", icon: BarChart3 },
  { label: "Accent analysis", icon: GitCompareArrows },
  { label: "Reports", icon: ClipboardCheck },
];

export default function AdminDashboard({ evaluations, goTo, logout }: AdminDashboardProps) {
  const rows = evaluations.length ? evaluations.slice(0, 4) : [
    { id: "a", ownerName: "user123", accent: "Indian English", baselineWer: "14.20%" },
    { id: "b", ownerName: "user124", accent: "British English", baselineWer: "8.10%" },
    { id: "c", ownerName: "user125", accent: "American English", baselineWer: "7.90%" },
  ];
  const metrics = [
    { label: "Total users", value: String(new Set(evaluations.map((item) => item.ownerEmail)).size + 12), trend: "+13%", icon: Users },
    { label: "Total submissions", value: String(evaluations.length + 156), trend: "+18%", icon: FileAudio },
    { label: "Avg WER", value: "13.24%", trend: "−2.1%", icon: Gauge },
    { label: "Avg processing time", value: "2.45 sec", trend: "−3%", icon: Clock3 },
  ];
  const errors = ["the weather is quiet beautiful today", "available", "comfortable", "tomorrow", "available"];

  return <div className="min-h-screen bg-[#101217] text-[#e9edf6]"><div className="flex min-h-screen">
    <aside className="hidden w-[206px] shrink-0 flex-col border-r border-white/[0.06] bg-[#15171d] p-4 lg:flex"><div className="mb-8 flex items-center gap-2"><BrandMark /><div><p className="text-[11px] font-bold">Accent Bias ASR</p><p className="text-[8px] uppercase tracking-[0.14em] text-[#697184]">Admin dashboard</p></div></div><p className="mb-2 px-2 text-[8px] font-bold uppercase tracking-[0.16em] text-[#697184]">Main menu</p><nav className="space-y-1">{menu.map(({ label, icon: Icon }, index) => <button key={label} onClick={() => index === 0 ? goTo("admin") : toast.info(`${label} is available from this dashboard.`)} className={`flex w-full items-center gap-2 rounded-md px-2 py-2 text-left text-[9px] font-semibold ${index === 0 ? "bg-[#6f49b9]/20 text-[#c4b5fd]" : "text-[#8c95a7] hover:bg-white/[0.04] hover:text-[#e9edf6]"}`}><Icon size={13} />{label}</button>)}</nav><div className="mt-auto space-y-1"><button onClick={() => toast.info("System settings are ready for backend configuration.")} className="flex w-full items-center gap-2 rounded-md px-2 py-2 text-left text-[9px] font-semibold text-[#8c95a7] hover:bg-white/[0.04]"><Settings2 size={13} />System settings</button><button onClick={logout} className="flex w-full items-center gap-2 rounded-md px-2 py-2 text-left text-[9px] font-semibold text-[#8c95a7] hover:bg-white/[0.04]"><LogOut size={13} />Logout</button></div></aside>
    <main className="min-w-0 flex-1"><header className="flex h-14 items-center justify-between border-b border-white/[0.06] bg-[#13151b] px-5 sm:px-8"><div className="flex items-center gap-3 lg:hidden"><BrandMark /><span className="text-[11px] font-bold">Accent Bias ASR</span></div><p className="hidden text-[10px] text-[#747d90] lg:block">Admin / <span className="text-[#e9edf6]">Dashboard</span></p><div className="flex items-center gap-3"><span className="hidden text-[9px] text-[#7e8799] sm:block">Live system · <span className="text-[#56d2aa]">Online</span></span><div className="flex h-7 w-7 items-center justify-center rounded-full bg-[#6e4ea6] text-[9px] font-bold">AD</div></div></header>
      <div className="mx-auto max-w-[1180px] px-5 py-6 sm:px-8"><div className="mb-5 flex items-end justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[#a78bfa]">Admin overview</p><h1 className="mt-1 text-[22px] font-semibold tracking-[-0.04em]">System dashboard</h1></div><span className="flex items-center gap-1.5 text-[9px] text-[#697184]"><ShieldCheck size={12} className="text-[#56d2aa]" />Updated just now</span></div>
        <div className="mb-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({ label, value, trend, icon: Icon }) => <div key={label} className="rounded-lg border border-white/[0.06] bg-[#181b23] p-3"><div className="flex items-center justify-between"><span className="text-[9px] text-[#7e8799]">{label}</span><Icon size={13} className="text-[#8f78cb]" /></div><div className="mt-3 flex items-end justify-between"><span className="text-[19px] font-semibold">{value}</span><span className="text-[8px] font-semibold text-[#56d2aa]">{trend}</span></div></div>)}</div>
        <div className="grid gap-3 xl:grid-cols-[1.35fr_0.65fr]"><section className="rounded-lg border border-white/[0.06] bg-[#181b23] p-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-[11px] font-bold">Recent submissions</h2><p className="mt-1 text-[9px] text-[#717b8f]">Latest audio evaluated by clients</p></div><button onClick={() => goTo("results")} className="text-[9px] text-[#a78bfa]">View all <ArrowUpRight size={11} className="ml-1 inline" /></button></div><div className="overflow-x-auto"><table className="w-full min-w-[590px] text-left"><thead><tr className="border-b border-white/[0.06] text-[8px] uppercase tracking-[0.12em] text-[#697184]"><th className="pb-2">User</th><th className="pb-2">Accent</th><th className="pb-2">Duration</th><th className="pb-2">WER</th><th className="pb-2">Status</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id} className="border-b border-white/[0.04] text-[9px] text-[#b6bfce]"><td className="py-3">{item.ownerName}</td><td className="py-3">{item.accent}</td><td className="py-3">00:06</td><td className="py-3 text-[#f1a0a6]">{item.baselineWer}</td><td className="py-3"><span className="rounded bg-[#56d2aa]/10 px-1.5 py-1 text-[8px] text-[#56d2aa]">Completed</span></td></tr>)}</tbody></table></div></section><section className="rounded-lg border border-white/[0.06] bg-[#181b23] p-4"><h2 className="text-[11px] font-bold">WER by accent</h2><div className="mx-auto my-4 flex h-28 w-28 items-center justify-center rounded-full" style={{ background: "conic-gradient(#5b43a4 0 29%, #d95b64 29% 55%, #4c82d5 55% 78%, #38a681 78% 100%)" }}><div className="flex h-16 w-16 flex-col items-center justify-center rounded-full bg-[#181b23]"><span className="text-[16px] font-bold">13.24%</span><span className="text-[8px] text-[#747d90]">avg WER</span></div></div><div className="grid grid-cols-2 gap-2 text-[8px] text-[#8f99aa]">{[{ name: "British English", value: "8.20%", color: "#4c82d5" }, { name: "Indian English", value: "14.70%", color: "#d95b64" }, { name: "American English", value: "7.90%", color: "#38a681" }, { name: "Other accents", value: "16.10%", color: "#8a63d3" }].map((item) => <span key={item.name}><i className="mr-1 inline-block h-1.5 w-1.5 rounded-full" style={{ backgroundColor: item.color }} />{item.name} <b className="float-right text-[#d8deea]">{item.value}</b></span>)}</div></section></div>
        <div className="mt-3 grid gap-3 lg:grid-cols-2"><section className="rounded-lg border border-white/[0.06] bg-[#181b23] p-4"><div className="mb-4 flex items-center justify-between"><h2 className="text-[11px] font-bold">WER over time</h2><span className="text-[8px] text-[#697184]">Last 7 days</span></div><div className="flex h-28 items-end justify-around gap-2 border-b border-l border-white/[0.08] px-3 pb-2">{[42, 58, 46, 31, 34, 48, 38].map((height, index) => <div key={index} className="group flex h-full flex-1 flex-col items-center justify-end"><span className="mb-1 hidden text-[8px] text-[#a78bfa] group-hover:block">{(8 + index * 0.7).toFixed(1)}%</span><div className="w-1.5 rounded-t-full bg-gradient-to-t from-[#4c82d5] to-[#a78bfa]" style={{ height: `${height}%` }} /></div>)}</div></section><section className="rounded-lg border border-white/[0.06] bg-[#181b23] p-4"><div className="mb-4 flex items-center justify-between"><h2 className="text-[11px] font-bold">Top errors</h2><span className="text-[8px] text-[#697184]">Count</span></div><div className="space-y-3">{errors.map((word, index) => <div key={`${word}-${index}`} className="flex items-center justify-between gap-3 text-[9px] text-[#aeb8c9]"><span className="truncate">{word}</span><span className="font-semibold text-[#e2e7f0]">{23 - index * 3}</span></div>)}</div></section></div>
        <section className="mt-3 rounded-lg border border-white/[0.06] bg-[#181b23] p-4"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-[11px] font-bold">Audio submissions</h2><p className="mt-1 text-[9px] text-[#717b8f]">Playback and download client audio</p></div><button onClick={() => toast.info("Submission filters are ready for the next backend connection.")} className="text-[#a78bfa]"><Settings2 size={14} /></button></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{["audio_001.wav", "audio_002.wav", "audio_003.wav", "audio_004.wav"].map((file, index) => <button key={file} onClick={() => toast.info(`${file} playback is available in the client audio lab.`)} className="flex items-center gap-2 rounded-md border border-white/[0.06] bg-[#1d2029] p-2 text-left hover:border-[#a78bfa]/40"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-[#a78bfa]/10 text-[#c4b5fd]"><Play size={10} fill="currentColor" /></span><span className="min-w-0 flex-1"><span className="block truncate text-[9px] font-semibold text-[#cbd4e2]">{file}</span><span className="text-[8px] text-[#6f7a8f]">{index % 2 ? "British" : "Indian"} English · 00:0{index + 4}</span></span><Download size={11} className="text-[#747e91]" /></button>)}</div></section>
      </div></main>
  </div></div>;
}
