import { ArrowRight, ArrowUpRight, BarChart3, Download, FileAudio, FileText, Mic, UploadCloud, Users, Zap } from "lucide-react";
import { toast } from "sonner";
import type { Session, EvaluationRecord, View } from "@/pages/Index";

type ClientDashboardProps = {
  session: Session;
  evaluations: EvaluationRecord[];
  goTo: (view: View) => void;
  logout: () => void;
  downloadTextFile: (fileName: string, content: string) => void;
};

function BrandMark() {
  return <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-[#2f6dcc] to-[#7049b7] text-white shadow-sm"><span className="text-[13px] font-black">∿</span></div>;
}

export default function ClientDashboard({ session, evaluations, goTo, logout, downloadTextFile }: ClientDashboardProps) {
  const latest = evaluations[0];
  return <div className="min-h-screen bg-[#f5f7fb] text-[#17243d]">
    <header className="border-b border-[#dbe2ed] bg-white px-5 py-3 shadow-sm sm:px-8"><div className="mx-auto flex max-w-[1280px] items-center justify-between gap-4"><div className="flex items-center gap-2.5"><BrandMark /><div><p className="text-[12px] font-bold tracking-[-0.03em] text-[#17243d]">Accent Bias ASR</p><p className="text-[8px] uppercase tracking-[0.15em] text-[#8190a8]">Client workspace</p></div></div><nav className="hidden items-center gap-6 text-[10px] font-semibold text-[#64738e] md:flex"><button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} className="text-[#2f5ca8]">Home</button><button onClick={() => toast.info("AccentLens measures WER, CER, and model improvement by accent.")}>About</button><button onClick={() => document.getElementById("client-how")?.scrollIntoView({ behavior: "smooth" })}>How it works</button></nav><div className="flex items-center gap-3"><span className="hidden text-[10px] text-[#71809a] sm:block">{session.name}</span><button onClick={logout} className="rounded-md bg-[#2f6dcc] px-3 py-1.5 text-[9px] font-bold text-white shadow-sm transition hover:bg-[#2459ae]">Logout</button></div></div></header>
    <main className="mx-auto max-w-[1280px] px-5 py-6 sm:px-8"><div className="mb-4 flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[#4b76bd]">Client side · User</p><h1 className="mt-1 text-[20px] font-bold tracking-[-0.04em] text-[#17243d]">Accent bias analysis</h1></div><span className="rounded-full border border-[#b9d4fa] bg-[#eef6ff] px-3 py-1.5 text-[9px] font-semibold text-[#3470c4]">Ready to evaluate</span></div>
      <div className="grid gap-3 xl:grid-cols-[1.2fr_0.8fr]"><section className="rounded-xl border border-[#dce3ee] bg-white p-4 shadow-[0_8px_30px_rgba(40,66,111,0.06)]"><div className="mb-3 flex items-center justify-between"><h2 className="text-[12px] font-bold text-[#1d2b44]">1. Record or upload audio</h2><Mic size={14} className="text-[#316cca]" /></div><div className="grid gap-3 md:grid-cols-[1.1fr_0.9fr]"><div className="rounded-lg border border-[#e2e8f2] bg-[#fbfcfe] p-4 text-center"><div className="mx-auto flex h-28 items-center justify-center gap-[3px] rounded-lg bg-[#f1f6fd] px-4">{[22,36,19,47,29,55,38,63,34,49,24,44,32,58,40,28,51,36,61,27,45,34,55,29,39,23].map((height, index) => <span key={index} className="w-[3px] rounded-full bg-[#5a8bd7] opacity-70" style={{ height: `${height}%` }} />)}</div><p className="mt-3 font-mono text-[18px] font-bold text-[#1d2b44]">00:00:00</p><p className="mt-1 text-[9px] text-[#ee6e74]">● Recording idle</p><div className="mt-3 flex justify-center gap-2"><button onClick={() => goTo("analyze")} className="rounded-md bg-[#e94f54] px-3 py-2 text-[9px] font-bold text-white shadow-sm hover:bg-[#d94349]"><Mic size={11} className="mr-1 inline" />Open recorder</button><button onClick={() => goTo("analyze")} className="rounded-md border border-[#c7d8f1] px-3 py-2 text-[9px] font-bold text-[#376dbc] hover:bg-[#eff6ff]"><UploadCloud size={11} className="mr-1 inline" />Upload audio</button></div></div><div className="rounded-lg border border-[#e2e8f2] bg-[#fbfcfe] p-4"><p className="mb-3 text-[10px] font-bold text-[#263652]">Audio status</p><div className="space-y-2 text-[9px] text-[#6e7e98]"><p className="flex items-center justify-between"><span>Supported formats</span><strong className="text-[#334a70]">WAV · MP3 · M4A</strong></p><p className="flex items-center justify-between"><span>Max file size</span><strong className="text-[#334a70]">25 MB</strong></p><p className="flex items-center justify-between"><span>Transcription</span><strong className="text-[#2f9b78]">Ready</strong></p></div><button onClick={() => goTo("analyze")} className="mt-6 flex w-full items-center justify-center gap-2 rounded-md bg-[#2f6dcc] py-2.5 text-[9px] font-bold text-white hover:bg-[#2459ae]"><Zap size={12} />Start new analysis</button></div></div></section>
        <section className="rounded-xl border border-[#dce3ee] bg-white p-4 shadow-[0_8px_30px_rgba(40,66,111,0.06)]"><div className="mb-3 flex items-center justify-between"><h2 className="text-[12px] font-bold text-[#1d2b44]">2. Accent / speaker information</h2><Users size={14} className="text-[#316cca]" /></div><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-1">{[{ label: "Accent", values: ["Indian English", "American English", "Nigerian English", "Scottish English"] }, { label: "Age group", values: ["18–25", "26–40", "41–60"] }, { label: "Gender", values: ["Female", "Male", "Prefer not to say"] }, { label: "Native language", values: ["Hindi", "English", "Other"] }].map((field) => <label key={field.label} className="text-[9px] font-semibold text-[#6b7c99]">{field.label}<select className="mt-1.5 w-full rounded-md border border-[#d9e2ef] bg-white px-2.5 py-2 text-[10px] text-[#304467] outline-none focus:border-[#5b8dda]">{field.values.map((value) => <option key={value}>{value}</option>)}</select></label>)}</div><button onClick={() => goTo("analyze")} className="mt-4 flex w-full items-center justify-center gap-2 rounded-md bg-[#2f6dcc] py-2.5 text-[9px] font-bold text-white hover:bg-[#2459ae]">Submit & transcribe <ArrowRight size={12} /></button></section></div>
      <div className="mt-3 grid gap-3 lg:grid-cols-[1fr_1fr]"><section className="rounded-xl border border-[#dce3ee] bg-white p-4 shadow-[0_8px_30px_rgba(40,66,111,0.06)]"><div className="mb-3 flex items-center justify-between"><h2 className="text-[12px] font-bold text-[#1d2b44]">3. Transcription results</h2><FileText size={14} className="text-[#316cca]" /></div><div className="grid gap-3 md:grid-cols-2"><div><p className="mb-1.5 text-[9px] font-bold text-[#7890b3]">Reference transcript</p><div className="rounded-md bg-[#f3f6fa] p-3 text-[10px] leading-5 text-[#536784]">The weather is quiet beautiful today</div></div><div><p className="mb-1.5 text-[9px] font-bold text-[#7890b3]">ASR transcript</p><div className="rounded-md bg-[#f3f6fa] p-3 text-[10px] leading-5 text-[#536784]">The weather is <span className="font-bold text-[#e25d64]">quiet</span> beautiful today</div></div></div><button onClick={() => goTo("compare")} className="mt-3 flex items-center gap-1 text-[9px] font-bold text-[#316cca]">Open detailed comparison <ArrowUpRight size={11} /></button></section><section className="rounded-xl border border-[#dce3ee] bg-white p-4 shadow-[0_8px_30px_rgba(40,66,111,0.06)]"><h2 className="mb-3 text-[12px] font-bold text-[#1d2b44]">4. Performance metrics</h2><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[{ label: "WER", value: "12.50%", color: "#e35d65" }, { label: "CER", value: "6.80%", color: "#efb64d" }, { label: "Confidence", value: "91%", color: "#36a57e" }, { label: "Processing time", value: "2.31 sec", color: "#4b7ed0" }].map((item) => <div key={item.label} className="rounded-lg bg-[#f5f8fc] p-3 text-center"><p className="text-[8px] font-bold uppercase tracking-[0.1em] text-[#8090aa]">{item.label}</p><p className="mt-2 text-[15px] font-bold" style={{ color: item.color }}>{item.value}</p></div>)}</div></section></div>
      <div className="mt-3 grid gap-3 lg:grid-cols-[1.4fr_0.6fr]"><section className="rounded-xl border border-[#dce3ee] bg-white p-4 shadow-[0_8px_30px_rgba(40,66,111,0.06)]"><div className="mb-3 flex items-center justify-between"><h2 className="text-[12px] font-bold text-[#1d2b44]">5. Accent performance comparison</h2><BarChart3 size={14} className="text-[#316cca]" /></div><div className="flex h-36 items-end justify-around gap-3 rounded-lg bg-[#fbfcfe] px-4 pb-4 pt-3">{[{ label: "British", value: 8.2, color: "#4c82d5" }, { label: "Indian", value: 14.7, color: "#e3555d" }, { label: "American", value: 7.9, color: "#e3ad43" }, { label: "Other", value: 16.1, color: "#6f57c6" }].map((bar) => <div key={bar.label} className="flex h-full flex-1 flex-col items-center justify-end gap-1"><span className="text-[8px] font-bold text-[#5c6d89]">{bar.value.toFixed(1)}%</span><div className="w-8 rounded-t-md" style={{ height: `${bar.value * 5}%`, background: `linear-gradient(180deg,${bar.color},${bar.color}aa)` }} /><span className="text-[8px] text-[#7586a1]">{bar.label}</span></div>)}</div></section><section className="rounded-xl border border-[#dce3ee] bg-white p-4 shadow-[0_8px_30px_rgba(40,66,111,0.06)]"><h2 className="mb-3 text-[12px] font-bold text-[#1d2b44]">6. Download results</h2><div className="space-y-2"><button onClick={() => downloadTextFile("accentlens-transcript.txt", "The weather is quiet beautiful today")} className="flex w-full items-center justify-between rounded-md border border-[#d9e2ef] px-3 py-2 text-[9px] font-semibold text-[#4f6382] hover:bg-[#f3f7fd]">Download transcript <Download size={12} /></button><button onClick={() => downloadTextFile("accentlens-results.csv", "metric,value\nWER,12.50%\nCER,6.80%\nConfidence,91%")} className="flex w-full items-center justify-between rounded-md border border-[#d9e2ef] px-3 py-2 text-[9px] font-semibold text-[#4f6382] hover:bg-[#f3f7fd]">Download results <Download size={12} /></button><button onClick={() => goTo("results")} className="flex w-full items-center justify-between rounded-md border border-[#d9e2ef] px-3 py-2 text-[9px] font-semibold text-[#4f6382] hover:bg-[#f3f7fd]">Open report <ArrowUpRight size={12} /></button></div></section></div>
      <section id="client-how" className="mt-3 rounded-xl border border-[#dce3ee] bg-gradient-to-r from-[#eef7ff] to-[#f2efff] p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-[9px] font-bold uppercase tracking-[0.15em] text-[#4d79bc]">How it works</p><p className="mt-1 text-[11px] text-[#526582]">Record or upload → add speaker context → compare transcription → download evidence.</p></div><span className="rounded-full bg-white/80 px-3 py-1.5 text-[9px] font-semibold text-[#536c9b]">{latest ? `Last run: ${latest.fileName}` : "No saved runs yet"}</span></div></section>
    </main></div>;
}
